# define the containers
services:
  # name of the service/container
  web:
    # build docker image from Dockerfile in current directory
    build: .
    image: blog-app-image
    # give app user write permissions - <user_id:group_id>
    # user: "${UID:-1000}:${GID:-1000}" # env variables with default 1000
    # map ports - <host_port>:<container_port>
    ports:
      - "5000:5000" # Access app at http://localhost:5000
    # set env variable inside the container
    environment:
      - FLASK_ENV=production # Tells Flask to run in production mode (disables debug)
    # mount host dir to container path - <host_path>:<container_path>
    volumes:
      - ./instance:/app/instance # For SQLite database persistence
